#+TITLE: Laboratorio 5.
#+SUBTITLE: Cosas.
#+AUTHOR: Jhonny Lanzuisi
#+EMAIL: jalb97@gmail.com
#+STARTUP: latexpreview
#+TAGS: :uni:algo1lab:
#+LANGUAGE: es
#+OPTIONS: toc:2
#+LATEX_CLASS: article
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: "STIX General"
#+HTML_MATHJAX: cancel.js noErrors.js
#+SETUPFILE: /home/jhonny/git/org-mode/style.css.org

# ----LICENSE----
#  Copyright 2021 Jhonny Lanzuisi (jalb97@gmail.com)
#  More source files at github.com/JLanzuisi
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ---------------

* Prelaboratorio

** Ejercicio 1

El siguiente programa en GCL calcula la suma de los =N= elementos
de un array =A= de tipo entero.

#+BEGIN_SRC iphyton
const N: int;
var A: array [0,N) of int;
var i: int;

i := 0;
suma := 0;

{Invariante P: suma = (+ k: 0 <= k < i: A[i]) /\ 0 <= i < N}
{Cota t: N - i}

do i != N ->
   suma := suma + A[i];
   i := i + 1
od

{Postcondición Q: suma = + i: 0 <= i < N: A[i]}
#+END_SRC

** Ejercicio 2

El siguiente programa traduce el programa del ejercicio 1 a python.
Se define una función =summ= que suma las entradas de un arreglo de tipo entero.

#+BEGIN_SRC python
def summ(A: list):
    '''
    Sum the entries of a one dimensional integer list.

    args:
       A, a list of type int.
    
    output:
       summ, a variable holding the sum
    '''

    for i in A:
        assert isinstance(A[i], int)

    summ = 0

    for i in A:
        summ = summ + A[i]

    assert summ == sum(A)

    return summ

print(summ([1,2,3]))
#+END_SRC

#+RESULTS:

* Laboratorio