#+TITLE: Cuarta tarea
#+SUBTITLE: Segundo ejercicio, (iii) y (iv), de Arreglos y Subprogramas en GCL.
#+AUTHOR: Jhonny Lanzuisi
#+EMAIL: jalb97@gmail.com
#+TAGS: :uni:algo1:
#+LANGUAGE: es
#+OPTIONS: toc:2
#+LATEX_CLASS: article
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: "Neo Euler"
#+HTML_MATHJAX: cancel.js noErrors.js
#+SETUPFILE: /home/jhonny/git/org-mode/style.css.org
#+LATEX_HEADER: \subject{Algoritmos y estructuras I}
#+LATEX_HEADER: \titlehead{Universidad Simón Bolívar.\hfill Caracas, Venezuela.}

# ----LICENSE----
#  Copyright 2021 Jhonny Lanzuisi (jalb97@gmail.com)
#  More source files at github.com/JLanzuisi
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ---------------

#+BEGIN_EXPORT latex
{\let\thefootnote\relax
\footnotetext{
\sffamily\scriptsize
\noindent Copyright (C)  2021 Jhonny Lanzuisi.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license can be found at \url{https://www.gnu.org/licenses/fdl-1.3.en.html}.
}
}
#+END_EXPORT

* Parte (iii)

Queremos demostrar que la tripleta siguiente es correcta.

#+BEGIN_EXPORT latex
\newcommand{\tripleta}[3]{\{#1\}\quad #2 \quad\{#3\}}
\newcommand{\hint}[1]{\qquad \text{< #1 >}}
#+END_EXPORT

\begin{gather*}
\{b[0] \coloneqq 0 \land (\forall i\mid 0\leq i\leq 5: c[i] = i)\}\\
    b[c(3)-1] \coloneqq 0\\
        \{b[0] + b[1]\cdot b[2] = 0\},
\end{gather*}

** Demostración

Suponemos el antecedente y comenzamos por el consecuente:

#+begin_export latex
\begin{align*}
    & (b[0] + b[1]\cdot b[2] = 0)(b\coloneq (b;[c[3]-1]\colon0))\\
\equiv	& \hint{Sustitución textual}\\
    & (b;[c[3]-1]\colon0)[0] + (b;[c[3]-1]\colon0)[1]\cdot(b;[c[3]-1]\colon0)[2] = 0\\
\equiv	& \hint{Por hipótesis \(c[3] = 3\)}\\
    & (b;[3-1]\colon0)[0] + (b;[3-1]\colon0)[1]\cdot(b;[3-1]\colon0)[2] = 0\\
\equiv	& \hint{Aritmética}\\
    & (b;[2]\colon0)[0] + (b;[2]\colon0)[1]\cdot(b;[2]\colon0)[2] = 0\\
\equiv	& \hint{Sustituyendo el valor de la función excepto}\\
    & b[0] + b[1]\cdot0 = 0\\
\equiv	& \hint{\(a.0 = 0\) para todo \(a\) y \(b[0]\coloneqq0\) por hipótesis}\\
    & 0 = 0.
\end{align*}
#+end_export

* Parte (iv)
Queremos demostrar que la siguiente tripleta es correcta.

#+begin_export latex
\begin{gather*}
\{b[1] = 2\}\\
    b[b[1]] \coloneqq 3\, ;\, b[1] \coloneqq b[2] - b[1]\\
        \{b[1] > 0\}
\end{gather*}
#+end_export

** Demostración

Suponemos el antecedente y comenzamos por el consecuente (Demostración 2.1.1):

#+begin_export latex
\begin{align*}
    & (b[1] > 0)(b\coloneqq (b;1\colon b[2]-b[1]))\\
\equiv	& \hint{Sustitución textual}\\
    & (b;1\colon b[2]-b[1])[1] > 0\\
\equiv	& \hint{Sustituyendo el valor de la función excepto}\\
    & b[2] - b[1] > 0\\
\end{align*}
#+end_export

Tomamos el resultado anterior como predicado intermedio \(R\)
de la secuenciación, y continuamos con la demostración,
esta vez haciendo la sustitución de la asignación en \(R\).

Demostración 2.1.2:

#+begin_export latex
\begin{align*}
    & (b[2] - b[1] > 0)(b\coloneqq (b;b[1]\colon3))\\
\equiv	& \hint{Sustitución textual}\\
    & (b;b[1]\colon3)[2] - (b;b[1]\colon3)[1] > 0\\
\equiv	& \hint{\(b[1]=2\) por hipótesis}\\
    & (b;2\colon3)[2] - (b;2\colon3)[1] > 0\\
\equiv	& \hint{Sustituyendo el valor de la función excepto}\\
    & 3 - b[1] > 0\\
\equiv	& \hint{\(b[1]=2\) por hipótesis}\\
    & 3 - 2 > 0\\
\equiv	& \hint{Aritmética}\\
    & 1 > 0.
\end{align*}
#+end_export

** Programa anotado

#+BEGIN_SRC pascal
|[
{b[1] = 2}

b[b[1]] := 3
{b[2] - b[1] > 0, Demostración 2.1.2}
b[1] := b[2] - b[1]

{b[1] > 0, Demostración 2.1.1}
|]
#+END_SRC
