#+TITLE: Second week's read/writing.
#+SUBTITLE: Homework comprised of two writings: 3A & 3B. ID2131.
#+AUTHOR: Jhonny Lanzuisi
#+EMAIL: jalb97@gmail.com
#+TAGS: :uni:ing-mat:
#+LANGUAGE: es
#+OPTIONS: toc:2
#+LATEX_CLASS: article
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: "STIX General"
#+HTML_MATHJAX: cancel.js noErrors.js
#+SETUPFILE: /home/jhonny/git/org-mode/style.css.org
#+ODT_STYLES_FILE: "/home/jhonny/git/org-mode/odt-style-template.ott"
#+LATEX_HEADER: \asignatura{}

# ----LICENSE---
# Copyright 2021 Jhonny Lanzuisi (jalb97@gmail.com)
# More source files at github.com/JLanzuisi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# --------------

* Writing 3A
I believe that the Wikipedia article is the more complete,
and also the one with the best definition of mathematics of the three articles:
the one by G. H. Hardy.
This is mainly because the Wikipedia article incorporates various perspectives,
and even begins by clearly stating that a definition for the whole of mathematics
isn't a simple thing, and thus no general consensus is available.

I, for one thing, do not believe mathematics to be a science
(and I'm certainly not alone in this claim,
Paul Lockhart as a wonderful essay on this).
Mathematics is more like art or, if you're not very fond or the word 'art',
more like abstract thought.
It as to deal, solely, with abstractions and ideas.
In this sense, it would be closer to philosophy than to physics or chemistry.

The Merriam-Webster definition is at the same time lacking and too specific.
This is probably a consequence of it being made for a dictionary,
and thus being among hundreds, or thousand, of other words.

The Britannica article stars by defining it as the "science of structure",
and then goes on a rather lengthy (and interesting)
recount of the history of mathematics.

* Writing 3B

My own definition of mathematics would be something like:

#+BEGIN_QUOTE
Mathematics is the art of ideas.
#+END_QUOTE

Or, maybe,

#+BEGIN_QUOTE
Mathematics is the consequence of pure thought,
of pure abstraction.
It, then, is both the inevitable consequence of, and intrinsic to, reason.
It deals with ideas, their development and consequences.
It both creates new things, and studies the old.
#+END_QUOTE
