#+TITLE: Answers to the questions on the two grandmothers.
#+SUBTITLE:Second homework.
#+AUTHOR: Jhonny Lanzuisi
#+EMAIL: jalb97@gmail.com
#+TAGS: :uni::
#+LANGUAGE: es
#+OPTIONS: toc:2
#+LATEX_CLASS: article
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: "STIX General"
#+HTML_MATHJAX: cancel.js noErrors.js
#+SETUPFILE: /home/jhonny/git/org-mode/style.css.org
#+LATEX_HEADER: \asignatura{El Mundo de la Literatura en Inglés. IDE143.}

# ----LICENSE---
# Copyright 2021 Jhonny Lanzuisi (jalb97@gmail.com)
# More source files at github.com/JLanzuisi
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# --------------

* How is living at Grandma Del's different from living at home?
Grandma's house is a rural, old, place.
There's ``no TV'', they use oil lamps at night,
and the main source of entertainment seems to be people.
Either grandma Del, who seems to love her granddaughter very much,
making her clothes and dressing her in a proper a beautiful way to go to curch,
for example, or the other plethora of individuals that interact with our protagonist.

Grandma's house also got nice quirky people living nearby,
and everywhere you go (like church)
there seems to be a story to tell,
someone new to meet.
The ``special friend'' of the girl narrator, Ms Princess,
goes to church nearby.

Grandmas house's is more interesting, full of paintings and old stories,
like a book unfolding it's narrative.

Home seems to be more city-like.
More urban, and thus,
more impersonal.
There's no one noticeable going around the house,
no Sunday school and no church.
Even bedtime stories are less interesting,
coming from books instead of grandma's wits.

* Name 3 things about Grandma Del that she likes
Well, we could pick the following:

1. The fact that grandma Del takes good care of her, dressing her and making her clothes by hand.
2. The stories grandma tells her, all of them ``lovely stories'', every night.
3. Her sewing machine that, by being older and more ``mechanical'', 
seems funny and interesting at the same time.

* State 3 ways in which Grandma Elaine is different from Grandma Del
Well, grandma Elaine introduces herself to us (the readers) as being a ``entirely different generation''
from grandma Del, so it's no surprise they're so far apart.
It's really not a generational issue, more like they are very different people.
They're from a different /class/, not a different generation.

We could take the following three differences:
1. Grandma Elaine is from the city, or a more urban place.
   This means that, to her, grandma Del is no more than a old lady from the country side.
2. Grandma Elaine's not proud of being called grandmother, for it makes her sound old.
   To her, being reminded that she is somewhat old is like an insult,
   or at least something undesirable.
3. Elaine is not very religious at all, 
   and seems to disregard very easily everything related to religion.
   She's annoyed when some things she does are called 'sins',
   maybe rightfully so,
   but her personality seems way more egotistic.

In general the biggest difference is, I think, 
that Elaine doesn't care as much about the author nor does she take being a grandmother as important:
#+BEGIN_QUOTE
why Towser wants me to spend more time with her if she is never there when I go.
#+END_QUOTE

* What is Grandma Elaine's opinion of the physical appearance of the author?
She thinks the author looks like a tomboy,
that is,
she thinks the author looks like a boy and should change that immediately.
Her hair is ``tough as her father's'',
and she is dressed in a way that Elaine would not consider `feminine'.

Elaine seems to be ``angry'' about the fact the author's skin is somewhat dark!
Which is a common racist trope,
and shines light into the fact that Elaine is less of a friendly person,
she's someone I personally would rather stay away from.

* What is the author's attitude to Pearlie when she first meets her?
She's her best friend. She likes her very much.
The author's very aware of the consequences that being poor brings upon Pearlie.
She's amazed by them, because of how much different their lifes are.

But even though the author and Pearlie are from completely different social classes,
they can be good friends.
The author tries to help her when she can, for example.
Pearlie is not something to stay away from,
but a friend, and a good one at that.

* Does her attitude change? Why?
It surely does.
The whole play describes the journey of this sweet little girl
from the humane and old fashioned world of grandma Del
to the egotistic, hateful, and uncompassionate world of grandma Elaine or her Clearwater family.

This explains why now Pearlie seems to her like an ugly and dirty person,
dressed in rags with a family just as bad and starving.
She's not develop any kind of compassion for others,
especially for people poorer than her.
So when she has to confront this reality once again she hates it and prefers to ignore it.
To make it like she's not even there.

* How does she feel about her physical appearance after going to visit her cousins in Clearwater?
She ends up feeling ashamed of the way she looks.
Particularly of the color of her skin.
The incident where she's called ``nigger''
deeply impacts her and makes her feel awful.

She then sees this as a sign to try and be something that she simply is not,
to try and be like all this racist and classist people want her to be.

* How does her attitude to Grandma Del change at the end of the play? 
It changes for the same reason that her attitude towards Pearlie changes.
Grandma Del is no longer the good hearted care-taker that she used to love,
grandma is now a nuisance from a world she would rather forget
than understand.

At the end, the author realizes that she just doesn't fit in anymore
in grandma's Del world, that of humble and even poor people,
that in which is normal to have a dark skin color.

Her attitude changes from being complety enthusiastic about going to Del's house,
to figuring out the best way to skip going there altogether.