Notas sin orden de lo que se me ocurre.

* Dejar de usar telegram

es mejor plain text

* ocr para el kaldewaij

https://github.com/jbarlow83/OCRmyPDF

* reemplazar aliases con shell scripts
* no usar bashism
* CANCELED Meterme en cantv y ver si me antiende alguien
  CLOSED: [2021-02-24 mié 14:54]

* DONE googlear modulos arch
  CLOSED: [2021-02-25 Thu 09:56]

* instalar which key en emacs

investigar hercules

* groff intentar font N
* para eqn usar pdfmom con -e
* crear script para compilar groff

https://emacs.stackexchange.com/questions/4108/execute-external-script-upon-save-when-in-a-certain-mode

* probar cambios a negrita y de familia en eqn
* hacer plantilla para groff en yasnippet
* intentar bloques de código con números de linea

poner el toggle. CODE dentro del toggle .NUMBER_LINES 1 2

* poner caracteres de acento automáticamente al guardar. Investigar string-replace

https://emacs.stackexchange.com/questions/7435/automatically-capitalise-i-to-i

* emacs quitar evil y vim keys en general
* añadir lineas de numero al codigo. crear macro para bloques de código: .def CBLK end. Y cambiar el escape caracter con ec a @
* hacer colofón mas pequeño, poner nombres de programas en courier
* toallas y toallitas y cosas de mama

1878 el dolar

* esperar a tener internet y actualizar tablet a lineage 16
