#+TITLE: Cosas por hacer de la universidad.
#+AUTHOR: Jhonny Lanzuisi.
#+DATE: 2020.
#+FILETAGS: :uni:

* Enero marzo 2021
** CANCELED Repasar contenidos del trimestre
   CLOSED: [2021-01-17 dom 14:33]

   Repasar analisis

** Algoritmos
*** DONE Primera tarea corta de algo1
    CLOSED: [2021-01-18 Mon 20:06] DEADLINE: <2021-01-19 mar>

*** DONE Video prof ravelo (15 min)
    CLOSED: [2021-01-18 Mon 20:07] DEADLINE: <2021-01-19 mar>

*** DONE Primer ejercicio sencillo.
    CLOSED: [2021-01-22 Fri 21:06] DEADLINE: <2021-01-25 lun>

*** Exámenes parciales.
**** 1er parcial (25%).
     DEADLINE: <2021-02-04 jue>

**** 2do parcial.
     DEADLINE: <2021-03-04 jue>

**** 3er parcial.
     DEADLINE: <2021-04-06 mar>

** Laboratorio de Algoritmos
*** Laboratorios
**** DONE Lab sem 2
     CLOSED: [2021-01-22 Fri 21:06] DEADLINE: <2021-01-26 mar>

*** Exámenes parciales
**** Primer parcial (20%).
     DEADLINE: <2021-02-10 mié>

**** Segundo parcial (30%).
     DEADLINE: <2021-03-10 mié>

** Analisis
*** Ejercicios de la guia.
**** TODO Ejercicios de integrales
     SCHEDULED: <2021-02-01 lun>

*** Exámenes parciales.
**** Primer parcial 35%.
     DEADLINE: <2021-02-08 lun>

**** Segundo parcial 35%.
     DEADLINE: <2021-03-08 lun>

**** Tercer parcial 30%.
     DEADLINE: <2021-04-07 mié>

*** TODO Videos de la profe semanas 1 y 2
    SCHEDULED: <2021-01-28 jue>

Los vídeos están en su canal de youtube. el whatsapp dice cuales son

** General
*** DONE primera tarea del gen, ver en el classroom
    CLOSED: [2021-01-19 Tue 12:01] SCHEDULED: <2021-01-18 lun>

*** TODO gen segunda tarea
    DEADLINE: <2021-01-29 Fri>

** Ingles
*** TODO Ing Mat Tarea semana 2
    DEADLINE: <2021-01-31 dom>
